### ISSUE TITLE
 Documentation: Create docs on how to join the BPD Leadership Council

### ISSUE THREAD

**Issue by activus-d** [BlackPythonDevs/blackpythondevs#104]
In [/how_to/join_leadership_council.md](https://github.com/BlackPythonDevs/blackpythondevs/blob/main/how_to/join_leadership_council.md), we need to document the process for community members to join the BPD Leadership Council. The created docs should outline eligibility criteria and application procedures.

Current Leadership Council members or community members willing to collaborate on our [Discord](https://discord.gg/XUc3tFqCT3) to gather accurate information can take on this task.

**Comment by TimOsahenru** [comment]
Hello @activus-d what's the source of truth for updating the `how_to/join_leadership_council.md` file. i.e is there a guide, constitution or something ?

**Comment by activus-d** [comment]
@TimOsahenruWe currently don't have any written guide on how to join the BPD Leadership Council. So the source of truth would be collaborating and asking questions from community leaders on our [Discord](https://discord.gg/XUc3tFqCT3).

**Comment by TimOsahenru** [comment]
Are these all the leaders we have? Please confirm, so we can start reaching out to them

![image](https://github.com/user-attachments/assets/606a4157-f74b-4d05-8fd3-ebaf4a238a6d)

**Comment by TimOsahenru** [comment]
Can we also confirm what positions are considered leadership roles (other than the four in the image above). I have listed some tho, LOL

List of some potential leadership roles
- Community manager
- Creative manager
- Social media manager

Or maybe we just begin with the ones available first. Please confirm this as well

**Comment by TimOsahenru** [comment]
We could create a questionnaire out of these questions and ask the respective leaders via chat/call

#### Questions to ask
**Leadership Pathways:**
- How did you come into your current leadership role
- Any formal processes or informal paths to assuming this position
- Advice for someone aspiring to move into this role
- Skills and Competencies:

**Skills or competencies essential for this role**
- How did you develop the skills needed for your role
- Specific training you recommend for this position

**Experience and Background:**
- Any work experience or background needed for this role. If yes please list

**Culture and Expectations:**
- What are the expectations for leaders assuming this role regarding behavior, decision-making, and communication, …

**Challenges and Opportunities:**
- What are some of the common challenges you face in current leadership role and solutions to them if any
- Opportunities/gains in assuming this leadership role. Please add any modification you deem fit @activus-d

**Comment by activus-d** [comment]
@kjaymiller can you please take a look at these comments?

**Comment by kjaymiller** [comment]
The Leadership Council and BPD Leaders are different folks.

The Leadership Council are recognized folks voted from existing Council Members. 

These are folks that are leaders in their local or other online Python Communities. 

They advise the BPD leaders but they are not a part of BPD Leadership.

**Comment by kjaymiller** [comment]
@activus-d @TimOsahenru - https://github.com/BlackPythonDevs/blackpythondevs/blob/main/roles/leadership-councilmembers.md for more information

**Comment by TimOsahenru** [comment]
Thanks for the clarification @kjaymiller 

@activus-d I believe this repository https://github.com/BlackPythonDevs/blackpythondevs/tree/main/roles/leadership already contains all the documents requested in this issue. Could you please confirm if that's correct? If so, can we go ahead to close it?.

If not, I think we should add some more details to this issue, and also update the issue description to say BPD leadership instead and rename the `join_leadership_council.md` file to `join_bpd_leadership.md`. Thanks

**Comment by activus-d** [comment]
@TimOsahenru So, we actually have a leadership team named the Black Python Devs `Leadership Council`, which is different from the `Leadership Team` in the screenshot you shared. This issue is about documenting what the `Leadership Council` is, its eligibility criteria, application procedures, and responsibilities.

To get the information on eligibility criteria, application procedures and responsibilities, please reach out to council members and community leaders like @kjaymiller on our Discord. I recommend reaching out to leaders/members on Discord because it's more accessible, especially for our members who don't use GitHub.

**Comment by kjaymiller** [comment]
@TimOsahenru  - Leadership Roles are appointed by the executor or vice executor.

**Comment by activus-d** [comment]
> Leadership Council are recognized folks voted from existing Council Members

@kjaymiller I would like some clarification on this. You mentioned that members of the Leadership Council are "voted from existing Council members." When you say "Council members," are you referring to members of the Leadership Council itself? In other words, are new members of the Leadership Council elected from among the current members of that same council? Or do we have another "Council" apart from the "Leadership Council"?

**Comment by kjaymiller** [comment]
>  When you say "Council Members," are you referring to members of the Leadership Council itself?

Yes

**Comment by TimOsahenru** [comment]
Based on the convo in this thread, I think it's clear that:
1. The Legacy council leadership and BPD leadership are two separate entities.
2. For now we shouldn't concern ourselves with the affairs of the Legacy council leadership or its members because, although they act as mentors to our leaders, they are not officially a part of the BPD.
3. Leadership positions within the BPD are determined by the Executor and Vice Executor and also the eligibility criteria for these positions are at their discretion, and details about the current roles of the leaders can be found [here](https://github.com/BlackPythonDevs/blackpythondevs/tree/main/roles) 

#### Action items
1. Change the file name and description of this issue to reflect BPD leadership
2. Close the issue as the concerns raised have all been answered already @activus-d @kjaymiller do we close this ?

**Comment by activus-d** [comment]
@TimOsahenru To ensure transparency and public accessibility, it's important that we document all aspects related to how the BPD is run and governed. Although the Leadership Council plays only an advisory role, it remains an important part of BPD community governance. So, I believe it's still important to document the process of joining the BPD Leadership Council.

**Comment by activus-d** [comment]
I'm currently working on this issue and will make a pull request soon.
