### ISSUE TITLE
Fix Typo on Leadership Summit Safety Guidelines

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs#126]
from - https://github.com/BlackPythonDevs/blackpythondevs/blob/main/programs/BPD%20Leadership%20Summit.md#public-health-policy

> We also recommend that any person who has tested positive in the week prior to the event and will offer resources to participate for free virtually.

should read

> We also request that any person who has tested positive in the week prior to the event not attend in person and will offer resources for them to participate for free virtually.

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller I think this issue should be closed. It seems someone submitted a PR for it and it got merged
