### ISSUE TITLE
Replace Issue Template

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs#134]
The template is not being used. 

Instead we can replace it with a more generic one.

This is a template that I have suggested in discussions like #128.

- title: What should resolving this issue accomplish in one sentence.
- description: a short (couple sentences why this is needed and reference any longer discussions that support this)
- ~~system information (if applicable): information like Python Version and Operating System~~
- ~~how to replicate (if applicable): steps to replicate the issue~~
- how to fix (if applicable or known)

There are some **task** objects that need to be added. I suggest that we

- [X] Make a task label

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller  can you assign me to this
