### ISSUE TITLE
Black Python Devs Conf 2025

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs#28]
Just a place to get the conversation started.

## Things to address
- [ ] Platform for presenting talks and doing interviews
- [ ] Platform for CFPs and talk scheduling
- [ ] Design for conference and website
- [ ] prospectus

**Comment by ronnzw** [comment]
Should we not push this to next year?

**Comment by kjaymiller** [comment]
@ronnzw yes the plan was to push this to the fall of 2025 and be a virtual conference

**Comment by kjaymiller** [comment]
Closing as this idea has been pushed to at least 2025
