### ISSUE TITLE
Update the mission of the group to updated content

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs#95]
New Mission Text 

> “Extending the ecosystem of Python Communities to Black and Colo(u)red Communities around the world.“

Places where this will need to be updated:

- [ ] The README of this repo.
- [ ] The About page of the website
- [ ] The Banner of the homepage (I believe this may change with a redesign)

**Comment by TimOsahenru** [comment]
@kjaymiller please assign this issue to me. For clarity

I don't see a mission statement in the README file of this repo, I'll just go ahead to creating one with a heading **MISSION STATEMENT** with text “Extending the ecosystem ...“ underneath

Also, did a text search in the about page for the text “extending the … “ and no search comes up, I’ll also be adding the heading **MISSION STATEMENT** in the about page - Please confirm and approve this

As for the banner in the homepage there’s no need to redesign the banner, the file edit can be done from the `en.yml` file. Please confirm if I can begin with these implementations

**Comment by kjaymiller** [comment]
go ahead

**Comment by TimOsahenru** [comment]
Hello @kjaymiller, it seems this issue would have been more appropriate for the https://github.com/BlackPythonDevs/blackpythondevs.github.io repo. Nonetheless, I've made a PR https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/383

**Comment by kjaymiller** [comment]
It needs to updated in all the places... there should have been another issue made for the website but this works.
